= Red Hat FUSE - SAGA-EIP using LRA coordinator demo

이 데모는 3개의 마이크로 서비스를 red hat fuse 7.8을 사용하였습니다.https://access.redhat.com/documentation/en-us/red_hat_fuse/7.8/[Red Hat Fuse 7.8]:

* `demo-service`: saga를 시작하고 다른 마이크로서비스를 호출하는 메인 마이크로서비스
* `order-service`: 새 주문을 item 명과 수량과 함께 생성
* `stock-service`: inventory/catalog를 관리. item별 적정 수량이 있는지 확인. 가능한 재고(stock)으로 부터 요청된 수량을 예약하고 재고에서 차감.

재고 카탈로그는 2가지 아이템으로 초기화 되어 있습니다.

[%autowidth,cols="1,1"]
|===
| ItemID | 재고 수량

|car | 40
|bike | 100
|=== 


차 3대 구매 요청 예제
[source,bash,options="nowrap",subs="attributes+"]
----
curl -X POST "http://localhost:8180/camel/purchases/car/3" -H  "accept: application/json"
----



stock-service는 ItemId를 찾지 못하거나 재고 수량이 없을 경우 에러를 리턴 합니다.

NOTE: 2개의 마이크로 서비스가 호출된 후 SAGA 보상(compensation)을 호출하기 위함 입니다. `demo-service` 에 재고 수량이 *27*일 경우 강제적으로 에러가 발생하도록 설정되어 있습니다..

Browse the API's Swagger page: open the root web page for every microservice and click on the link to review the API.

== Narayana LRA Coordinator

This DEMO implements link:https://microservices.io/patterns/data/saga.html[SAGA EIP] using orchestration.

The coordinator used is implemented by Narayana, meeting the  link:https://github.com/eclipse/microprofile-lra[Eclipse MicroProfile specification]. See the link: link:https://narayana.io/lra/[Long Running Actions (LRA)]


Related links:

* link:https://hub.docker.com/r/jbosstm/lra-coordinator/[Docker Hub lra-coordinator image]
* link:https://github.com/jboss-dockerfiles/narayana/tree/master/lra/lra-coordinator[Dockerfile for lra-coordinator]
* link:https://github.com/jboss-dockerfiles/narayana[Narayana Docker and OpenShift artifacts]
* link:https://access.redhat.com/documentation/en-us/red_hat_fuse/7.8/html/apache_camel_development_guide/saga-eip[Red Hat Fuse - Apache Camel Development Guide - Chapter 9. Saga EIP]


== Deployment options

You can run this demo in the following modes:

* OpenShift
* Standalone on your machine


For more details about running the project on OpenShift, CI/CD deployments, as well as the rest of the runtime, see the link:http://appdev.openshift.io/docs/spring-boot-runtime.html[Spring Boot Runtime Guide].

IMPORTANT: Fuse 7.X requires Java 8 JDK


== Running the demo on OpenShift cluster

Fuse images are required for building the application image. The following steps will create a new project, import base images, and finally using link:https://www.eclipse.org/jkube/docs/openshift-maven-plugin[JKube] the application is built and deployed.


. Log in to your OpenShift cluster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
oc login -u developer -p developer
----

. Create a new OpenShift project for the demo:
+
[source,bash,options="nowrap",subs="attributes+"]
----
oc new-project MY_PROJECT_NAME
----

. Deploy the LRA Coordinator POD using the link:https://github.com/jboss-dockerfiles/narayana/tree/master/lra/openshift-template[template]:
+
[source,bash,options="nowrap",subs="attributes+"]
----
oc create -f lra-coordinator-template.yaml

oc new-app --template=lra-coordinator -e LOG_LEVEL=DEBUG
----

. Import base images into your newly created project (MY_PROJECT_NAME):
+
[source,bash,options="nowrap",subs="attributes+"]
----
oc import-image fuse-java-openshift:1.8 --from=registry.access.redhat.com/fuse7/fuse-java-openshift:1.8 -n $(oc project -q) --confirm
----

. Build and deploy every microservice to the OpenShift project/namespace:
+
[source,bash,options="nowrap",subs="attributes+"]
----
mvn clean -DskipTests oc:deploy -Popenshift -Djkube.generator.fromMode=istag -Djkube.generator.from=$(oc project -q)/fuse-java-openshift:1.8
----

. In your browser, navigate to the `MY_PROJECT_NAME` project in the OpenShift console.
Wait until you can see that all POD applications have started up.

. Retrieve the URL for the `demo-service` application.
+
[source,bash,options="nowrap",subs="attributes+"]
----
oc get route demo-service -o jsonpath='http://{.spec.host}{"\n"}'
----

. Open the URL to access the `demo-service` application and then follow the instructions on that page.

. Undeploy the project when it is not longer needed
+
[source,bash,options="nowrap",subs="attributes+"]
----
mvn oc:undeploy -Popenshift
----

== Running the demo standalone on your machine

To run this demo as a standalone project on your local machine:


. Start a local LRA-Coordinator
+
[source,bash,options="nowrap",subs="attributes+"]
----
podman run --name lra-coordinator -p 8080:8080 -e LOG_LEVEL=DEBUG jbosstm/lra-coordinator
----

. Build the whole project:
+
[source,bash,options="nowrap",subs="attributes+"]
----
cd PROJECT_DIR

mvn clean package
----

. Run all the services (execute the command using different shells, for every microservice POM module):
+
[source,bash,options="nowrap",subs="attributes+"]
----
mvn spring-boot:run
----
. Go to link:http://localhost:8180[] and then follow the instructions on that page.
