= Red Hat FUSE - SAGA-EIP using LRA coordinator demo

이 데모는 3개의 마이크로 서비스를 red hat fuse 7.8을 사용하였습니다.https://access.redhat.com/documentation/en-us/red_hat_fuse/7.8/[Red Hat Fuse 7.8]:

* `demo-service`: saga를 시작하고 다른 마이크로서비스를 호출하는 메인 마이크로서비스
* `order-service`: 새 주문을 item 명과 수량과 함께 생성
* `stock-service`: inventory/catalog를 관리. item별 적정 수량이 있는지 확인. 가능한 재고(stock)으로 부터 요청된 수량을 예약하고 재고에서 차감.

재고 카탈로그는 2가지 아이템으로 초기화 되어 있습니다.

[%autowidth,cols="1,1"]
|===
| ItemID | 재고 수량

|car | 40
|bike | 100
|=== 


차 3대 구매 요청 예제
[source,bash,options="nowrap",subs="attributes+"]
----
curl -X POST "http://localhost:8180/camel/purchases/car/3" -H  "accept: application/json"
----



stock-service는 ItemId를 찾지 못하거나 재고 수량이 없을 경우 에러를 리턴 합니다.

NOTE: 2개의 마이크로 서비스가 호출된 후 SAGA 보상(compensation)을 호출하기 위함 입니다. `demo-service` 에 재고 수량이 '27'일 경우 강제적으로 에러가 발생하도록 설정되어 있습니다..

Browse the API's Swagger page: 각 마이크로 서비스의 root web page를 열어서 링크를 클릭하면 API 리뷰가 가능 합니다.

== Narayana LRA Coordinator

이 데모는 SAGA orchestration을 구현하였습니다. link:https://microservices.io/patterns/data/saga.html[SAGA EIP]

coordinator는 Narayana으로 구현되었습니다. link:https://github.com/eclipse/microprofile-lra[Eclipse MicroProfile specification].
LRA(Long Running Actions) 방식을 사용 합니다.: link:https://narayana.io/lra/[Long Running Actions (LRA)]


관련 사항:

* link:https://hub.docker.com/r/jbosstm/lra-coordinator/[Docker Hub lra-coordinator image]
* link:https://github.com/jboss-dockerfiles/narayana/tree/master/lra/lra-coordinator[Dockerfile for lra-coordinator]
* link:https://github.com/jboss-dockerfiles/narayana[Narayana Docker and OpenShift artifacts]
* link:https://access.redhat.com/documentation/en-us/red_hat_fuse/7.8/html/apache_camel_development_guide/saga-eip[Red Hat Fuse - Apache Camel Development Guide - Chapter 9. Saga EIP]


== 배포 옵션

아래 옵션 사용이 가능 합니다.

* OpenShift
* Standalone on your machine

== OpenShift cluster에서 데모 구동

Fuse 이미지는 application 이미지를 빌드하기 위해 필요 합니다. 아래 스텝은 새로운 프로젝트를 만들고 base 이미지를 import 합니다.
그리고 마지막으로 link:https://www.eclipse.org/jkube/docs/openshift-maven-plugin[JKube]를 사용해서 빌드/배포 합니다.


. OpenShift cluster 로그인:
+
[source,bash,options="nowrap",subs="attributes+"]
----
oc login -u developer -p developer
----

. 데모 프로젝트 생성:
+
[source,bash,options="nowrap",subs="attributes+"]
----
oc new-project MY_PROJECT_NAME
----

. LRA Coordinator POD 배포 link:https://github.com/jboss-dockerfiles/narayana/tree/master/lra/openshift-template[template]을 이용:
+
[source,bash,options="nowrap",subs="attributes+"]
----
oc create -f lra-coordinator-template.yaml

oc new-app --template=lra-coordinator -e LOG_LEVEL=DEBUG
----

. base 이미지 import (MY_PROJECT_NAME):
+
[source,bash,options="nowrap",subs="attributes+"]
----
oc import-image fuse-java-openshift:1.8 --from=registry.access.redhat.com/fuse7/fuse-java-openshift:1.8 -n $(oc project -q) --confirm
----

. Build and deploy every microservice to the OpenShift project/namespace:
+
[source,bash,options="nowrap",subs="attributes+"]
----
mvn clean -DskipTests oc:deploy -Popenshift -Djkube.generator.fromMode=istag -Djkube.generator.from=$(oc project -q)/fuse-java-openshift:1.8
----

. In your browser, navigate to the `MY_PROJECT_NAME` project in the OpenShift console.
Wait until you can see that all POD applications have started up.

. Retrieve the URL for the `demo-service` application.
+
[source,bash,options="nowrap",subs="attributes+"]
----
oc get route demo-service -o jsonpath='http://{.spec.host}{"\n"}'
----

. Open the URL to access the `demo-service` application and then follow the instructions on that page.

. Undeploy the project when it is not longer needed
+
[source,bash,options="nowrap",subs="attributes+"]
----
mvn oc:undeploy -Popenshift
----

== Running the demo standalone on your machine

To run this demo as a standalone project on your local machine:


. Start a local LRA-Coordinator
+
[source,bash,options="nowrap",subs="attributes+"]
----
podman run --name lra-coordinator -p 8080:8080 -e LOG_LEVEL=DEBUG jbosstm/lra-coordinator
----

. Build the whole project:
+
[source,bash,options="nowrap",subs="attributes+"]
----
cd PROJECT_DIR

mvn clean package
----

. Run all the services (execute the command using different shells, for every microservice POM module):
+
[source,bash,options="nowrap",subs="attributes+"]
----
mvn spring-boot:run
----
. Go to link:http://localhost:8180[] and then follow the instructions on that page.
